name: Android Fastlane With Firebase App Distribution

on:
  push:
    branches:
      - main

jobs:
  distribution_to_firebase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Step 3: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Step 4: Setup Ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.9"
          bundler-cache: true

      # Step 5: Install Ruby dependencies (Fastlane)
      - name: Install Ruby dependencies
        working-directory: android
        run: bundle install

      # Step 6: Build & distribute with Fastlane
      - name: Build And Distribution
        working-directory: android
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: bundle exec fastlane firebase_distribution
